version: '3'
services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - server
    networks:
      - weather-app

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/weather-app
    depends_on:
      - mongodb
    networks:
      - weather-app

  mongodb:
    image: mongo:6-jammy
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - weather-app

volumes:
  mongo_data:

networks:
  weather-app:
    driver: bridge
