version: '3'
services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - VITE_API_BASE_URL=http://localhost:4000/api
    depends_on:
      - server
    networks:
      - weather-app
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    environment:
      - PORT=4000
      - CLIENT_URL=http://localhost:3000
      - MONGODB_URL=mongodb://mongodb:27017/weather-app
      - JWT_SECRET=<<key>>
      - JWT_VERIFY_EMAIL_EXPIRATION_MINUTES=10
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=<<email>>
      - SMTP_PASSWORD=<key>>
      - EMAIL_FROM=<<email>>
      - WEATHER_API_KEY=<key>>
      - BASE_WEATHER_API_URL=https://api.weatherapi.com/v1
    depends_on:
      - mongodb
    networks:
      - weather-app

  mongodb:
    image: mongo:6-jammy
    container_name: mongodb
    ports:
      - '27018:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - weather-app

volumes:
  mongo_data:

networks:
  weather-app:
    driver: bridge
